import monstera from "../assets/img/monstera.jpg";

export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    cover: monstera,
    light: 3,
    water: 1,
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    cover: monstera,
    light: 2,
    water: 3,
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    cover: monstera,
    light: 2,
    water: 1,
    isSpecialOffer: true,
  },
  {
    name: "yucca",
    category: "classique",
    cover: monstera,
    id: "4kk",
    light: 3,
    water: 2,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    cover: monstera,
    light: 1,
    water: 3,
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    cover: monstera,
    light: 3,
    water: 1,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    light: 1,
    cover: monstera,
    water: 3,
    isSpecialOffer: true,
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    cover: monstera,
    isSpecialOffer: true,
    light: 2,
    water: 1,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    cover: monstera,
    light: 0,
    water: 2,
  },
];
